### ISSUE TITLE
Controller on gesture flipcard

### ISSUE THREAD

**Issue by chrislaurie-io** [imtheguna/flutter_flip_card#2]
I need to flip a gesture flipcard back programmatically. The controller functionality is only available on the normal flipcard. Is there a way to flip the gesture flipcard in code - say from my state manger.

I have another tap gesture on the flipcard,  so I cannot use the normal flipcard.

**Comment by imtheguna** [comment]
hey,

I added the Controller future enabled for GestureFlipCard please update package in your pubspec.yaml then you can access gesture flipcard using programmatically

` final controller = GestureFlipCardController();`

```
 GestureFlipCard(
              controller: controller, // used to ccontrol the Gesture flip programmatically
              axis: FlipAxis.vertical,
              enableController: true, // if [True] if you need flip the card using programmatically
              animationDuration: const Duration(seconds: 3),
              frontWidget: Center(
                child: Container(
                  height: 200,
                  width: 140,
                  child: Image.asset(
                    'image/01.png',
                    fit: BoxFit.fitHeight,
                  ), ), ),
              backWidget: Container(
                height: 200,
                width: 140,
                child: Image.asset(
                  'image/02.jpg',
                  fit: BoxFit.fitHeight,
                ),),
)
```

**Comment by chrislaurie-io** [comment]
I'm afraid I cannot get this to work. The card does not flip on the flipCard function call. Here is my scenario: I have a gridview with cards on them. Each card is a gesture flip card. This works and I can flip manually with no problem.  My cardWidh=get looks like this: 

```
Widget _flipCard (){
    final fcController = GestureFlipCardController();
    return GestureFlipCard(
      controller: fcController,
      enableController: true,
      frontWidget: _trackCard(),
      backWidget: _trackActionsCard(fcController),
    );
}
```

My scenario is this: I have a grid of these cards and each one is a gesture flip card. This works fine. 

The GestureFlipCardController is passed into the _trackActions widget, which in turn passes it to the state manager. This is where the controller.flipcard() is eventually called from. All my widgets are stateless widgets, so that might also be the problem. TextEditingCOntrollers live & work happily this way, though.

I have tried moving the flipcard instantiation to a class property and calling it off a button, and that did not work either.

Also, I would like the initial flip to happen by gesture and then flip it back programmatically. If I understand the above example, correctly, then I cannot do that combination. It could work if can get access to which side is facing uo at the moment through a isFront or similar property.

**Comment by imtheguna** [comment]
if the enableController = true you can access the card using programmatically also gesture mode and if it's false then you can access only gesture mode. I hope it' will not work for stateless widgets. I will add the state return future in next release. can you share your code/sample code so I can check that.

**Comment by chrislaurie-io** [comment]
That's great! I'll see if I can knock together a sample.
