### ISSUE TITLE
any ways to disable inkwell effect? (background bit changes when tapping to flip)

### ISSUE THREAD

**Issue by nasangyeop** [imtheguna/flutter_flip_card#3]
any options for this issue?

**Comment by imtheguna** [comment]
Could you kindly provide additional details or a sample related to this issue? I'll review it promptly.

**Comment by nasangyeop** [comment]
> any options for this issue?

`import 'package:flutter/material.dart';
import '../modal/flip_side.dart';
import '../controllers/flip_card_controllers.dart';
import 'dart:math';

/// [FlipCard] A component that provides a flip card animation

class FlipCard extends StatefulWidget {
  /// [controller] used to ccontrol the flip
  final FlipCardController controller;

  ///[frontWidget] The Front side widget of the card
  final Widget frontWidget;

  ///[backWidget] The Back side widget of the card
  final Widget backWidget;

  /// [onTapFlipping]  When enabled, the card will flip automatically when touched.
  final bool onTapFlipping;

  /// [axis] The flip axis [Horizontal] and [Vertical]
  final FlipAxis axis;

  /// [rotateSide] The card rotate side
  final RotateSide rotateSide;

  /// [animationDuration] The amount of milliseconds a turn animation will take.
  final Duration animationDuration;

  **/// [disableSplashEffect] The option for disable Inkwell widget's splash effect.
  final bool disableSplashEffect;**

  const FlipCard(
      {Key? key,
      this.onTapFlipping = false,
      required this.frontWidget,
      required this.backWidget,
      required this.controller,
      this.axis = FlipAxis.vertical,
      required this.rotateSide,
      this.animationDuration = const Duration(milliseconds: 800),
      this.disableSplashEffect = false})
      : super(key: key);

  @override
  FlipCardState createState() => FlipCardState();
}

class FlipCardState extends State<FlipCard> with TickerProviderStateMixin {
  late AnimationController animationController;
  final flipCardController = FlipCardController();
  bool isFront = true;
  double anglePlus = 0;
  @override
  void initState() {
    super.initState();
    animationController =
        AnimationController(duration: widget.animationDuration, vsync: this);
    widget.controller.state = this;
    flipCardController.state = this;
  }

  @override
  void dispose() {
    animationController.dispose();
    super.dispose();
  }

  ///Flip the card
  Future filpCard() async {
    if (animationController.isAnimating) return;
    isFront = !isFront;
    await animationController.forward(from: 0).then((value) => anglePlus = pi);
  }

  @override
  Widget build(BuildContext context) => AnimatedBuilder(
      animation: animationController,
      builder: (context, child) {
        double piValue = 0.0;
        if (widget.rotateSide == RotateSide.top ||
            widget.rotateSide == RotateSide.left) {
          piValue = pi;
        } else {
          piValue = -pi;
        }
        double angle = animationController.value * piValue;
        late Matrix4 transform;
        late Matrix4 transformForBack;
        if (isFront) angle += anglePlus;
        if (widget.axis == FlipAxis.horizontal) {
          transform = Matrix4.identity()
            ..setEntry(3, 2, 0.001)
            ..rotateX(angle);
          transformForBack = Matrix4.identity()..rotateX(pi);
        } else {
          transform = Matrix4.identity()
            ..setEntry(3, 2, 0.001)
            ..rotateY(angle);
          transformForBack = Matrix4.identity()..rotateY(pi);
        }

        return InkWell(
          onTap: widget.onTapFlipping == false
              ? null
              : () {
                  flipCardController.state!.filpCard();
                },
          **splashFactory: widget.disableSplashEffect
              ? NoSplash.splashFactory
              : null,**
          child: Transform(
              alignment: Alignment.center,
              transform: transform,
              child: isFrontWidget(angle.abs())
                  ? widget.frontWidget
                  : Transform(
                      transform: transformForBack,
                      alignment: Alignment.center,
                      child: widget.backWidget,
                    )),
        );
      });

  bool isFrontWidget(double angle) {
    const degrees90 = pi / 2;
    const degrees270 = 3 * pi / 2;
    return angle <= degrees90 || angle >= degrees270;
  }
}
`

i have no authority for pr, so i just leave the comment for some enhancements for you package.

**Comment by nasangyeop** [comment]
> Could you kindly provide additional details or a sample related to this issue? I'll review it promptly.

flip_card.dart

```
/// [disableSplashEffect] The option for disable Inkwell widget's splash effect.
final bool disableSplashEffect;

const FlipCard(
      {Key? key,
      this.onTapFlipping = false,
      required this.frontWidget,
      required this.backWidget,
      required this.controller,
      this.axis = FlipAxis.vertical,
      required this.rotateSide,
      this.animationDuration = const Duration(milliseconds: 800),
      this.disableSplashEffect = false})
      : super(key: key);
```
 
```
return InkWell(
  onTap: widget.onTapFlipping == false
      ? null
      : () {
          flipCardController.state!.filpCard();
        },
  splashFactory: widget.disableSplashEffect
      ? NoSplash.splashFactory
      : null,
  child: Transform(
      alignment: Alignment.center,
      transform: transform,
      child: isFrontWidget(angle.abs())
          ? widget.frontWidget
          : Transform(
              transform: transformForBack,
              alignment: Alignment.center,
              child: widget.backWidget,
            )),
);
```


i have no authority for pr, so i just leave the comment for some enhancements for you package.

I hope this helps.

**Comment by nasangyeop** [comment]
and i think these enhancements would be useful too.

flip_card.dart
```
bool getIsFront() {
  return isFront;
}
```

flip_card_controllers.dart
```
class FlipCardController {
  FlipCardState? state;

  /// Flip the card
  Future flipcard() async => state?.filpCard();
  /// Flip card current state (front/back)
  bool? getIsFront() => state?.getIsFront();
}
```

I'm sorry for modifying your package. I just left a comment because there was a feature I wanted to add while using your package. Have a nice day.

**Comment by imtheguna** [comment]
Hi,

Thanks for the contributions, I have added the SplashEffect, splashColor, and focusColor in FlipCard. please use 

flutter_flip_card: ^0.0.5

**Comment by imtheguna** [comment]
Will add getIsFront in the next release.
